// Expenses, their recurring templates, and the per-month notes that sit
// alongside them. Every handler is (data, payload) => data and must stay pure:
// ids are generated by the action creators in App.jsx and arrive in the
// payload, so a handler run twice with the same input gives the same output.

import { applyExpenseDeletion } from '../utils/dataTransforms.js';

export const expenseHandlers = {
  'expense/add': (data, expense) => ({
    ...data,
    expenses: [...data.expenses, expense],
  }),

  'expense/update': (data, { id, updates }) => ({
    ...data,
    expenses: data.expenses.map((e) => (e.id === id ? { ...e, ...updates } : e)),
  }),

  // Routed through applyExpenseDeletion because deleting an auto-generated
  // expense also has to record the month on its template.
  'expense/delete': (data, { id }) => applyExpenseDeletion(data, id),

  'expense/addGenerated': (data, expenses) =>
    expenses.length === 0 ? data : { ...data, expenses: [...data.expenses, ...expenses] },

  'recurring/add': (data, recurring) => ({
    ...data,
    recurrings: [...(data.recurrings ?? []), recurring],
  }),

  'recurring/delete': (data, { id }) => ({
    ...data,
    recurrings: (data.recurrings ?? []).filter((r) => r.id !== id),
  }),

  'note/set': (data, { year, month, text }) => ({
    ...data,
    monthlyNotes: {
      ...(data.monthlyNotes ?? {}),
      [year]: { ...(data.monthlyNotes?.[year] ?? {}), [month]: text },
    },
  }),
};
